swagger: '2.0'
basePath: /v1
host: 127.0.0.1

info:
  version: 0.0.1
  title: Room Seeker APIs
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
    
paths:
  /auth/login:
    post:
      tags: 
        - Authentication
      parameters:
        - in: body
          name: loginInfo
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
            
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string
                example: email/password is empty
        
  /auth/signup:
    post:
      tags:
        - Authentication
      parameters:
        - in: body
          name: signupInfo
          schema:
            type: object
            properties:
              userName:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
            
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string
                
  /accountSetting/changeUserInfo:
    post:
      tags:
        - Account Management
      parameters:
        - in: header
          name: Authorization
          type: string
        - in: body
          name: userInfo
          schema:
            type: object
            properties:
              userName:
                type: string
              firstName:
                type: string
              lastName:
                type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string  
                
  /accountSetting/changePassword:
    post:
      tags:
        - Account Management
      parameters:
        - in: header
          name: Authorization
          type: string
        - in: body
          name: ChangePassword
          schema:
            type: object
            properties:
              previousPassword:
                type: string
              newPassword:
                type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string 
                
  /Review/writeReview:
    post:
      tags:
        - Review System
      parameters:
        - in: header
          name: Authorization
          type: string
        - in: body
          name: writeReview
          schema:
            type: object
            properties:
              orderId:
                type: string
              review:
                type: string
              mark:
                type: number

      responses:
        200:
          description: OK
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string 
                
  /accountSetting/accountInfo:
    get:
      tags:
        - Account Management
      parameters:
        - in: header
          name: Authorization
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              password:
                type: string
              username:
                type: string
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string
  /search:
    post:
      tags:
        - Searching System
      parameters:
        - in: body
          name: searchInput
          schema:
            type: object
            properties:
              searchbar:
                type: string
              check-in-date:
                type: string
              check-out-date:
                type: string
              guests-number:
                type: integer
              city:
                type: string
              price:
                type: integer
              parking:
                type: boolean
              air-conditioner:
                type: boolean
              wi-fi:
                type: boolean
              kitchen:
                type: boolean
              sortBy:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                title:
                  type: string
                price:
                  type: number
                description:
                  type: string
                id:
                  type: integer
                oneImage:
                  type: string

  /property/information:
    post:
      tags:
        - Property Management
      parameters:
        - in: header
          name: Authorization
          type: string
        - in: body
          name: detail
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              address:
                type: string
              city:
                type: string
              openDate:
                type: string
              closeDate:
                type: string
              price:
                type: number
              guests:
                type: integer
              parking:
                type: boolean
              airConditioner:
                type: boolean
              wifi:
                type: boolean
              kitchen:
                type: boolean
              photos:
                type: array
                items:
                  type: string
                
                
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              roomId:
                type: integer
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string    
                
                
  /order/createOrder:
    post:
      tags:
        - Order Management
      parameters:
        - in: header
          name: Authorization
          type: string
        - in: body
          name: detail
          schema:
            type: object
            properties:
              roomId:
                type: integer
              checkIn:
                type: string
              checkOut:
                type: string
              guests:
                type: integer
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              orderId:
                type: integer
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string    
                
                
  /order/myOrder:

    get:
      tags:
        - Order Management
      parameters:
        - in: header
          name: Authorization
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                title:
                  type: string
                price:
                  type: number
                description:
                  type: string
                id:
                  type: string
                checkIn:
                  type: string
                checkOut:
                  type: string
                guests:
                  type: integer
                roomId:
                  type: integer
                oneImage:
                  type: string
                status:
                  type: string
                rating:
                  type: number
                review:
                  type: string
              
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string    
                
  /order/myHostOrder:
    get:
      tags:
        - Order Management
      parameters:
        - in: header
          name: Authorization
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                title:
                  type: string
                price:
                  type: number
                description:
                  type: string
                id:
                  type: string
                checkIn:
                  type: string
                checkOut:
                  type: string
                guests:
                  type: integer
                roomId:
                  type: integer
                oneImage:
                  type: string
                status:
                  type: string
              
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string    
                
                
  /host/myPost:
    get:
      tags:
        - Property Management
      parameters:
        - in: header
          name: Authorization
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                title:
                  type: string
                price:
                  type: number
                description:
                  type: string
                id:
                  type: integer
                oneImage:
                  type: string
              
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string    
                
  /account/myRecommendation:
    
    get:
      tags:
        - Recommendation System
      parameters:
        - in: header
          name: Authorization
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                title:
                  type: string
                price:
                  type: number
                description:
                  type: string
                id:
                  type: integer
                oneImage:
                  type: string
              
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string   
                
  /account/myWishlist:
    get:
      tags:
        - Wishlist System
      parameters:
        - in: header
          name: Authorization
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                title:
                  type: string
                price:
                  type: number
                description:
                  type: string
                id:
                  type: integer
                oneImage:
                  type: string
              
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string   
          
  /account/putWish:
    post:
      tags:
        - Wishlist System
      parameters:
        - in: header
          name: Authorization
          type: string
        - in: body
          name: room
          schema:
            type: object
            properties:
              roomId:
                type: integer
      responses:
        200:
          description: OK
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string 
                
  /account/removeWish:
    post:
      tags:
        - Wishlist System
      parameters:
        - in: header
          name: Authorization
          type: string
        - in: body
          name: room
          schema:
            type: object
            properties:
              roomId:
                type: integer
      responses:
        200:
          description: OK
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string 
                
    
        
            
                
  /property/reviews:
    post:
      tags:
        - Review System
      parameters:
        - in: body
          name: detail
          schema:
            type: object
            properties:
              propertyId:
                type: integer
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                mark:
                  type: integer
                review:
                  type: string
              
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string 
                
  /property/info:
    
    post:
      tags:
        - Property Management
      parameters:
        - in: body
          name: propertyId
          schema:
            type: object
            properties:
              propertyId:
                type: integer
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              city:
                type: string
              openDate:
                type: string
              closeDate:
                type: string
              price:
                type: integer
              guests:
                type: integer
              parking:
                type: boolean
              airConditioner:
                type: boolean
              wifi:
                type: boolean
              kitchen:
                type: boolean
              address:
                type: string
              mark:
                type: number
              photos:
                type: array
                items:
                  type: string
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              errorMessage:
                type: string 
        
        
  /message:
    get:
      tags:
        - Message System
      parameters:
        - in: header
          name: Authorization
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                messageType:
                  type: string
                orderId:
                  type: integer
                  
  /confirmOrder:
    post:
      tags:
        - Order Management
      parameters:
        - in: header
          name: Authorization
          type: string
        - in: body
          name: confirmBody
          schema:
            type: object
            properties:
              orderId:
                type: integer
              confirmType:
                type: string
      responses:
        200:
          description: OK
    
  /chatbot:
    post:
      tags:
        - Chatbot
      parameters:
        - in: header
          name: Authorization
          type: string
        - in: body
          name: chatbotBody
          schema:
            type: object
            properties:
              utterance:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              answer:
                type: string

